# Generated by Django 4.0.2 on 2022-02-18 04:18

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='code',
            field=models.CharField(db_index=True, default=chat.models.generate_code, max_length=10),
        ),
    ]
